version: '3.8'

services:

  server:
    image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./src/api:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mariadb

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src/api:/var/www/html:ro
    env_file:
      - ./env/api.env

  mariadb:
    image: mariadb
    env_file:
      - ./env/mariadb.env
    volumes:
      - database:/var/lib/mysql

  react:
    build:
      context: .
      dockerfile: dockerfiles/react.dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./src/web_app:/app:ro
    stdin_open: true
    tty: true
    depends_on:
      - server

  expo:
    build:
      context: .
      dockerfile: dockerfiles/expo.dockerfile
    ports:
      - 19000:19000 
      - 19001:19001
      - 19002:19002
    env_file:
      - ./env/expo.env
    volumes:
      - /app/node_modules
      - ./src/mobile_app:/app:ro
      - ./src/mobile_app/.expo:/app/.expo
    stdin_open: true
    tty: true
    depends_on:
      - server

  #FOR TYPESCRIPT LINTING DURING DEVELOPEMENT:
  update_react_modules:
    build:
      context: .
      dockerfile: dockerfiles/update_react_modules.dockerfile
    volumes:
      - ./src/web_app/node_modules:/app/node_modules
  update_expo_modules:
    build:
      context: .
      dockerfile: dockerfiles/update_expo_modules.dockerfile
    volumes:
      - ./src/mobile_app/node_modules:/app/node_modules

volumes: 
  database: {}
